"""empty message

Revision ID: 773046e0a637
Revises: 4bfdefa7daee
Create Date: 2023-12-15 12:03:02.158560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '773046e0a637'
down_revision: Union[str, None] = '4bfdefa7daee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Unicode(length=50),
               existing_nullable=True)
    op.alter_column('users', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.Unicode(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
